version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app_ml
    ports:
      - "8000:8000"
    env_file:
      - ml-variables.env
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
    network_mode: host